Fix error if container count set as string
`rake create_loader_and_run_tests[20]`
cause
```
NoMethodError: undefined method `times' for "20":String
```