Fix error if container count set as string (#20)
* Fix error if container count set as string

`rake create_loader_and_run_tests[20]`
cause
```
NoMethodError: undefined method `times' for "20":String
```

* Fail early if container_count not string